export const labels = {

    relax_countdown: "Relax countdown",
    work_countdown: "Work countdown",
    start_work: "Start work",
    stop_work: "Stop work",
    round_end: "Round end",
    workout_end: "Workout end",
    work_warning: "Work warning",
    relax_warning: "Relax warning",

    signal_for: "Предупреждение за",

    last_signal_options: [
        "Последни 20[с]",
        "Последни 10[с]",
        "Последни 5[с]"
    ],

    last_relax: "Последна почивка",
    workout: "Тренировка",
    work: "Работа",
    relax: "Почивка",
    rounds: "Рундове",
    delay: "Отл. старт[с]",
    use_first_round: "Използвай само първи рунд",
    use_first_base: "Използвай само първа база",
    bases: "Бази",
    relaxes: "Почивки[с]",
    round_prefix: "Рунд ",
    seconds_suffix: "[с]",
    total_time: "Общо време",
    saved_workouts: "Запазени тренировки",
    workout_name: "Име на тренировка",
    select_workout: "Избери тренировка",
    go_to_workout: "Напред към таймер",
    delete: "Изтрий",
    successful_delete: "Успешно изтрита тренировка",
    workout_settings: "Тренировка - настройки",
    warning_between_1_and_50: "Моля въведете стойност между 1 и 50",
    save_workout: "Запазване на тренировка",
    enter_valid_name: "Моля въведете име",
    file_already_exists: "Тренировка с това име вече съществува",
    sounds_settings: "Настройка на звуци",
    successful_reset: "Успешно нулиране",
    reset: "Нулирай",
    resume: "Продължи",
    start: "Старт",
    pause: "Пауза",
    round: "Рунд",
    base: "База",
    elapsed_time: "Изминало време",
    remaining_time: "Оставащо време",
    signals: "Сигнали",
    save: "Запази",
    prepare: "Подготовка",
    system_error: "Системна грешка",
    sounds: "Звуци",

    successful_save: "Успешно запазване",
    error_save: "Грешка при запазване"
}
