export const labels = {

    relax_countdown: "Relax countdown",
    work_countdown: "Work countdown",
    start_work: "Start work",
    stop_work: "Stop work",
    round_end: "Round end",
    workout_end: "Workout end",
    work_warning: "Work warning",
    relax_warning: "Relax warning",
    between_rounds_warning: "Between rounds warning",
    between_rounds_countdown: "Between rounds countdown",
    last_base_signal: "Last base signal",

    signal_for: "Предупреждение за",

    last_signal_options: [
        "Последни",
        "Последни",
        "Последни"
    ],

    last_relax: "Последна почивка",
    workout: "Тренировка",
    work: "Работа",
    relax: "Почивка",
    rounds: "Рундове",
    delay: "Отл. старт",
    use_first_round: "Използвай само първи рунд",
    use_first_base: "Използвай само първа база",
    bases: "Бази",
    relaxes: "Почивки[с]",
    round_prefix: "Рунд ",
    seconds_suffix: "[с]",
    total_time: "Общо време",
    saved_workouts: "Запазени тренировки",
    workout_name: "Име на тренировка",
    select_workout: "Избери тренировка",
    go_to_workout: "Напред към таймер",
    delete: "Изтрий",
    warning_between_1_and_50: "Моля въведете стойност между 1 и 50",
    save_workout: "Запазване на тренировка",
    enter_valid_name: "Моля въведете име",
    file_already_exists: "Тренировка с това име вече съществува",
    reset: "Нулирай",
    resume: "Продължи",
    start: "Старт",
    pause: "Пауза",
    round: "Рунд",
    base: "База",
    elapsed_time: "Изминало време",
    remaining_time: "Оставащо време",
    signals: "Сигнали",
    save: "Запази",
    prepare: "Подготовка",
    system_error: "Системна грешка",

    sounds_settings: "Настройка на звуци",
    workout_settings: "Тренировка - настройки",

    successful_save: "Успешно запазване",
    successful_reset: "Успешно нулиране",
    successful_delete: "Успешно изтриване",

    generic_error: "Възникна грешка. Моля опитай отново.",

    device_sleep: "Заспиване на устройство",
    turned_on: "Включено",
    turned_off: "Изключено",

    version: "Версия",
    date: "Дата",
    os: "ОС",

    filename: "Име на файл",
    creation_date: "Дата на създаване",
    history: "История",
    table_contains_only_results_from: "Таблицата съдържа резултати от последните",
    days: "дни",
    load_full_history: "Зареди пълна история",
    actions: "Действия",
    workout_preview: "Преглед на тренировка",
    play_workout_confirmation_message: "Сиргурни ли сте, че искате да заредите тренировката? Ще загубите текущо заредената!",
    play_workout_confirmation_header: "Зареждане на тренировка",
    load: "Зареди",
    reject: "Отказ",
    timer: "Таймер"
}
